### ISSUE TITLE
POST example

### ISSUE THREAD

**Issue by fretn** [morlad/netw#1]
Can you add an example where you post data to a server ?

I try to post data to a url: https://www.mydomain.com/somepage.php?action=postform

and then I add two fields to the body of the request:

"\nsomedata%3Ddata%26otherdata%3Ddata" but that doesn't work

(and I'm using the NETW_VERB_POST verb)

**Comment by fretn** [comment]
found the problem: `in_bytes` shouldn't be empty

**Comment by morlad** [comment]
You can look at a working example at https://github.com/morlad/minimod/blob/2c2ff704ca84b628858abb8476cab960f187a0db/src/minimod.c#L1186
Make sure you set the headers correctly and the leading line-break in your body is probably not what you want. But without knowing your code or what your server expects it is hard to tell.
